### ISSUE TITLE
2.0.0.Final not in https://repository.jboss.org/org/switchyard/switchyard-parent/ ?

### ISSUE THREAD

**Issue by dougtoppin** [jboss-switchyard/quickstarts#451]
I am not sure if this is really an issue or not but should 2.0.0.Final be found in https://repository.jboss.org/org/switchyard/switchyard-parent/ now?
If so I am not seeing it or else I'm doing something wrong.

**Comment by cunningt** [comment]
We're working on the release of 2.0.0.Final and have changed versions to 2.0.0.Final.   We need to resolve https://issues.jboss.org/browse/SWITCHYARD-2672 before releasing though, so bear with us.
